[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ultimate_project = "A4KcpT3paxY6w29djfA8fyinXJw3iMRB5GjhNwWkpoQW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
